fix safe link attribution retrieval
With some nodes you got errors like:
```
    if output.links is not None and len(output.links) > 0:
       ^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'links'
```
or
```
    if input.link is None:
       ^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'link'
```
After adding `getattr` with `default` as `None` it works without any problem.